// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAsZip(arg1) {
  return window['go']['main']['App']['ExportAsZip'](arg1);
}

export function ExportFiles(arg1) {
  return window['go']['main']['App']['ExportFiles'](arg1);
}

export function FilterFiles(arg1, arg2) {
  return window['go']['main']['App']['FilterFiles'](arg1, arg2);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetExportProgress() {
  return window['go']['main']['App']['GetExportProgress']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ScanFiles(arg1) {
  return window['go']['main']['App']['ScanFiles'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}
