// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {main} from '../models';

export function ExportAsZip(arg1:scanner.ExportOptions):Promise<scanner.ExportResult>;

export function ExportFiles(arg1:scanner.ExportOptions):Promise<scanner.ExportResult>;

export function FilterFiles(arg1:Array<scanner.FileInfo>,arg2:main.FilterOptions):Promise<main.FilterResult>;

export function GetDrives():Promise<Array<main.DriveInfo>>;

export function GetExportProgress():Promise<scanner.ExportProgress>;

export function OpenFolder(arg1:string):Promise<void>;

export function ScanFiles(arg1:scanner.ScanOptions):Promise<scanner.ScanResult>;

export function SelectDirectory():Promise<string>;

export function SelectExportDirectory():Promise<string>;
